# Generated by Django 5.1.3 on 2024-11-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=10)),
                ('castrado', models.BooleanField(default=False)),
                ('fiv_felv', models.CharField(choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=10)),
                ('vacinado', models.BooleanField(default=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='gatos/')),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
